export type NdElement =
  HTMLElement
  | HTMLAllCollection
  | HTMLAnchorElement
  | HTMLAppletElement
  | HTMLAreaElement
  | HTMLAudioElement
  | HTMLBaseElement
  | HTMLBaseFontElement
  | HTMLBodyElement
  | HTMLBRElement
  | HTMLButtonElement
  | HTMLCanvasElement
  | HTMLDivElement
  | HTMLDataElement
  | HTMLDataListElement
  | HTMLDetailsElement
  | HTMLDialogElement
  | HTMLDirectoryElement
  | HTMLDListElement
  | HTMLEmbedElement
  | HTMLFieldSetElement
  | HTMLFormElement
  | HTMLFontElement
  | HTMLFrameElement
  | HTMLFrameSetElement
  | HTMLHeadElement
  | HTMLHeadingElement
  | HTMLHtmlElement
  | HTMLHRElement
  | HTMLImageElement
  | HTMLInputElement
  | HTMLIFrameElement
  | HTMLLIElement
  | HTMLLabelElement
  | HTMLLinkElement
  | HTMLLegendElement
  | HTMLMainElement
  | HTMLMapElement
  | HTMLMarqueeElement
  | HTMLMediaElement
  | HTMLMenuElement
  | HTMLMetaElement
  | HTMLMeterElement
  | HTMLModElement
  | HTMLOptGroupElement
  | HTMLObjectElement
  | HTMLOListElement
  | HTMLOptionElement
  | HTMLOrSVGElement
  | HTMLOrSVGImageElement
  | HTMLOrSVGScriptElement
  | HTMLOutputElement
  | HTMLParagraphElement
  | HTMLParamElement
  | HTMLPictureElement
  | HTMLPreElement
  | HTMLProgressElement
  | HTMLQuoteElement
  | HTMLSpanElement
  | HTMLScriptElement
  | HTMLSelectElement
  | HTMLSlotElement
  | HTMLSourceElement
  | HTMLStyleElement
  | HTMLTableCaptionElement
  | HTMLTableDataCellElement
  | HTMLTextAreaElement
  | HTMLTableCellElement
  | HTMLTableColElement
  | HTMLTableElement
  | HTMLTableHeaderCellElement
  | HTMLTableRowElement
  | HTMLTableSectionElement
  | HTMLTemplateElement
  | HTMLTimeElement
  | HTMLTitleElement
  | HTMLTrackElement
  | HTMLUListElement
  | HTMLUnknownElement
  | HTMLVideoElement;
